name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs: 
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: true
      - name: Build collectd in docker
        run: |
          set -x
          RELEASE_VERSION="${GITHUB_REF##*/}"
          RELEASE_VERSION="${RELEASE_VERSION:1}"
          debugoutput="insights-collectd-debug-${RELEASE_VERSION}.tar.gz"
          outputgz="insights-collectd-${RELEASE_VERSION}.tar.gz"
          outputzip="insights-collectd-${RELEASE_VERSION}.zip"

          image=collectd-bundle
          docker build --build-arg insight_version=${RELEASE_VERSION} -t $image . 

          cid=$(docker create $image true)

          docker export $cid | tar --delete 'dev' 'proc' 'etc' 'sys' 'collectd-symbols' | gzip -f - > $outputgz
          docker export $cid | tar --delete 'dev' 'proc' 'etc' 'sys' 'collectd' | gzip -f - > $debugoutput
          tar xzf $outputgz && zip $outputzip $(tar ztf $outputgz)

          assets=()
          for asset in $outputzip $outputgz $debugoutput; do
            assets+=("-a" "$asset")
          done
      
          hub release create "${assets[@]}" -m "v$RELEASE_VERSION" "v$RELEASE_VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      